 DROP TABLE IF EXISTS view_events, view_events_url;

CREATE TABLE IF NOT EXISTS view_events
(
    event_id BIGINT NOT NULL,
    views INTEGER NOT NULL,
    CONSTRAINT event_id_pk PRIMARY KEY (event_id)
);

CREATE TABLE IF NOT EXISTS view_events_url
(
    view_events_url_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL,
    date_view TIMESTAMP NOT NULL,
    http_address VARCHAR(2000),
    ip_address VARCHAR(250)
);