--DROP TABLE IF EXISTS view_events_url;

CREATE TABLE IF NOT EXISTS view_events_url
(
    view_events_url_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app VARCHAR(2000),
    date_view TIMESTAMP NOT NULL,
    uri_address VARCHAR(2000),
    ip_address VARCHAR(250)
);